version: '3.8'
services:
  jupyter:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - .:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=True
      - NB_UID=1002
      - NB_GID=1002
      # - CHOWN_HOME=yes
      # - CHOWN_HOME_OPTS=-R
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8505:8501'
    volumes:
      - .:/home/jovyan
    command: streamlit run streamlit/speed_model.py
  streamlit-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8501:8501'
    volumes:
      - .:/home/jovyan
    command: streamlit run streamlit/app.py
