name: ookla-statcan-test
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - requests
  - python-dotenv
  - scikit-learn
  - matplotlib
  - notebook
  - jupyterlab
  - folium
  - plotly
  - pip
  - pip:
    - streamlit
    - streamlit-folium
    - OSMPythonTools
    - mapclassify